//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Election.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BureauVote
    {
        public int Id { get; set; }
        public string code { get; set; }
        public string lieu { get; set; }
    }
}
