//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Election.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Electeur
    {
        public int Id { get; set; }
        public string prenom { get; set; }
        public string nom { get; set; }
        public string cni { get; set; }
        public Nullable<byte> avoter { get; set; }
        public Nullable<int> candidat { get; set; }
        public Nullable<int> bureau { get; set; }
        public Nullable<int> compte { get; set; }
    }
}
